server.port=8814
spring.application.name=payment-service

# Kết nối Eureka Server (Máy bạn đang chạy ở 8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Cấu hình Database (Tạo database tên payment_db trước trong MySQL nhé)
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# VNPAY CONFIGURATION (User Demo Account)
vnpay.tmn-code=ZBLF58QJ
vnpay.hash-secret=XJP5GIOFBGLNCRW32598OJZ2LKBSKV8A
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment/vnpay-return

# MOMO CONFIGURATION (Sandbox Account)
momo.partner-code=MOMOBKUN20180529
momo.access-key=klm05TvNBqgWn6uA
momo.secret-key=at67qH6mk8w5Y1n71ytrSOfW5QYpSB80
momo.pay-url=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=http://localhost:5173/payment/vnpay-return
